// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comms.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Reply struct {
	// Types that are valid to be assigned to Payload:
	//	*Reply_Data
	//	*Reply_Error
	Payload              isReply_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

type isReply_Payload interface {
	isReply_Payload()
}

type Reply_Data struct {
	Data *Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type Reply_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Reply_Data) isReply_Payload() {}

func (*Reply_Error) isReply_Payload() {}

func (m *Reply) GetPayload() isReply_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Reply) GetData() *Data {
	if x, ok := m.GetPayload().(*Reply_Data); ok {
		return x.Data
	}
	return nil
}

func (m *Reply) GetError() *Error {
	if x, ok := m.GetPayload().(*Reply_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Reply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Reply_Data)(nil),
		(*Reply_Error)(nil),
	}
}

type Data struct {
	Number               uint64   `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetNumber() uint64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterType((*Reply)(nil), "grpc.Reply")
	proto.RegisterType((*Data)(nil), "grpc.Data")
	proto.RegisterType((*Error)(nil), "grpc.Error")
}

func init() { proto.RegisterFile("comms.proto", fileDescriptor_db39efb7717b7d47) }

var fileDescriptor_db39efb7717b7d47 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x3d, 0x53, 0xc4, 0x20,
	0x10, 0x0d, 0x0e, 0x5c, 0xe6, 0x96, 0xb1, 0xa1, 0x70, 0x32, 0x16, 0xce, 0xc9, 0x35, 0x57, 0x31,
	0xce, 0x59, 0xd8, 0xfb, 0x31, 0xa6, 0xb2, 0xa0, 0xb3, 0x24, 0xc9, 0x4e, 0x9a, 0x20, 0x08, 0xa4,
	0xc8, 0xbf, 0x77, 0x20, 0x49, 0x69, 0xf9, 0xf6, 0x7d, 0xec, 0xbe, 0x05, 0xde, 0x3b, 0x6b, 0xa3,
	0xf2, 0xc1, 0x25, 0x27, 0xe8, 0x18, 0x7c, 0x2f, 0xcf, 0x50, 0x6b, 0xfc, 0x9d, 0x31, 0x26, 0xd1,
	0x40, 0x6d, 0x31, 0x46, 0x33, 0x62, 0x43, 0x4e, 0xe4, 0x72, 0xd4, 0x3b, 0x94, 0xdf, 0xc0, 0x34,
	0xfa, 0x69, 0x11, 0x27, 0xa0, 0x83, 0x49, 0xa6, 0xf0, 0xfc, 0x0a, 0x2a, 0x47, 0xa8, 0x77, 0x93,
	0x4c, 0x5b, 0xe9, 0xc2, 0x88, 0x33, 0x30, 0x0c, 0xc1, 0x85, 0xe6, 0xa6, 0x48, 0xf8, 0x2a, 0xf9,
	0xc8, 0xa3, 0xb6, 0xd2, 0x2b, 0xf7, 0x7a, 0x84, 0xda, 0x9b, 0x65, 0x72, 0x66, 0x90, 0x0f, 0x40,
	0xb3, 0x5f, 0xdc, 0xc1, 0xe1, 0x67, 0xb6, 0x1d, 0x86, 0x92, 0x4d, 0xf5, 0x86, 0xe4, 0x23, 0xb0,
	0x62, 0xfe, 0xff, 0xba, 0xeb, 0x0b, 0xb0, 0xb7, 0xdc, 0x4b, 0x28, 0x80, 0x4f, 0x4c, 0x5f, 0xc5,
	0x18, 0xc5, 0xed, 0xba, 0x7a, 0x6b, 0x77, 0xcf, 0x77, 0xe8, 0xa7, 0x45, 0x56, 0x17, 0xf2, 0x44,
	0xba, 0x43, 0x79, 0xc4, 0xf3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0xe8, 0x87, 0x33, 0x17,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommsClient is the client API for Comms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommsClient interface {
	GetNumbers(ctx context.Context, opts ...grpc.CallOption) (Comms_GetNumbersClient, error)
}

type commsClient struct {
	cc *grpc.ClientConn
}

func NewCommsClient(cc *grpc.ClientConn) CommsClient {
	return &commsClient{cc}
}

func (c *commsClient) GetNumbers(ctx context.Context, opts ...grpc.CallOption) (Comms_GetNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Comms_serviceDesc.Streams[0], "/grpc.Comms/GetNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &commsGetNumbersClient{stream}
	return x, nil
}

type Comms_GetNumbersClient interface {
	Send(*Request) error
	Recv() (*Reply, error)
	grpc.ClientStream
}

type commsGetNumbersClient struct {
	grpc.ClientStream
}

func (x *commsGetNumbersClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commsGetNumbersClient) Recv() (*Reply, error) {
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommsServer is the server API for Comms service.
type CommsServer interface {
	GetNumbers(Comms_GetNumbersServer) error
}

func RegisterCommsServer(s *grpc.Server, srv CommsServer) {
	s.RegisterService(&_Comms_serviceDesc, srv)
}

func _Comms_GetNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommsServer).GetNumbers(&commsGetNumbersServer{stream})
}

type Comms_GetNumbersServer interface {
	Send(*Reply) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type commsGetNumbersServer struct {
	grpc.ServerStream
}

func (x *commsGetNumbersServer) Send(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commsGetNumbersServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Comms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Comms",
	HandlerType: (*CommsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNumbers",
			Handler:       _Comms_GetNumbers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "comms.proto",
}
