// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comms.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Reply struct {
	Number               int64    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_db39efb7717b7d47, []int{1}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "grpc.Request")
	proto.RegisterType((*Reply)(nil), "grpc.Reply")
}

func init() { proto.RegisterFile("comms.proto", fileDescriptor_db39efb7717b7d47) }

var fileDescriptor_db39efb7717b7d47 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xce, 0xcf, 0xcd,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0x52, 0xe6,
	0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x71, 0x95, 0xe4, 0xb9, 0x58,
	0x83, 0x52, 0x0b, 0x72, 0x2a, 0x85, 0xc4, 0xb8, 0xd8, 0xf2, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0xc0,
	0x2a, 0x98, 0x83, 0xa0, 0x3c, 0x23, 0x73, 0x2e, 0x56, 0x67, 0x90, 0xd1, 0x42, 0x7a, 0x5c, 0x5c,
	0xee, 0xa9, 0x25, 0x7e, 0x60, 0xd1, 0x62, 0x21, 0x5e, 0x3d, 0x90, 0x1d, 0x7a, 0x50, 0x0b, 0xa4,
	0xb8, 0x61, 0xdc, 0x82, 0x9c, 0x4a, 0x25, 0x06, 0x0d, 0x46, 0x03, 0xc6, 0x24, 0x36, 0xb0, 0x5b,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x18, 0xc3, 0x2d, 0x9a, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommsClient is the client API for Comms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommsClient interface {
	GetNumbers(ctx context.Context, opts ...grpc.CallOption) (Comms_GetNumbersClient, error)
}

type commsClient struct {
	cc *grpc.ClientConn
}

func NewCommsClient(cc *grpc.ClientConn) CommsClient {
	return &commsClient{cc}
}

func (c *commsClient) GetNumbers(ctx context.Context, opts ...grpc.CallOption) (Comms_GetNumbersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Comms_serviceDesc.Streams[0], "/grpc.Comms/GetNumbers", opts...)
	if err != nil {
		return nil, err
	}
	x := &commsGetNumbersClient{stream}
	return x, nil
}

type Comms_GetNumbersClient interface {
	Send(*Request) error
	Recv() (*Reply, error)
	grpc.ClientStream
}

type commsGetNumbersClient struct {
	grpc.ClientStream
}

func (x *commsGetNumbersClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commsGetNumbersClient) Recv() (*Reply, error) {
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommsServer is the server API for Comms service.
type CommsServer interface {
	GetNumbers(Comms_GetNumbersServer) error
}

func RegisterCommsServer(s *grpc.Server, srv CommsServer) {
	s.RegisterService(&_Comms_serviceDesc, srv)
}

func _Comms_GetNumbers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommsServer).GetNumbers(&commsGetNumbersServer{stream})
}

type Comms_GetNumbersServer interface {
	Send(*Reply) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type commsGetNumbersServer struct {
	grpc.ServerStream
}

func (x *commsGetNumbersServer) Send(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commsGetNumbersServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Comms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Comms",
	HandlerType: (*CommsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNumbers",
			Handler:       _Comms_GetNumbers_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "comms.proto",
}
